changelog:
  exclude:
    labels:
      - skip-changelog
      - duplicate
      - invalid
      - question
  categories:
    - title: Features
      labels:
        - feature
    - title: Fixes
      labels:
        - bug
    - title: Documentation
      labels:
        - documentation
    - title: Performance
      labels:
        - performance
    - title: Accessibility
      labels:
        - accessibility
    - title: Security
      labels:
        - security
    - title: Dependencies
      labels:
        - dependencies
    - title: Internal
      labels:
        - internal
    - title: Other Changes
      labels:
        - "*"
